/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*********************************************************************

                   This is a full QWERTY keyboard
                    with number entering capable

*********************************************************************/

#include <string.h>
#include "tail.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define  ID_WINDOW_0       (GUI_ID_USER + 1 )
#define  ID_BUTTON_1       (GUI_ID_USER + 2 )
#define  ID_BUTTON_2       (GUI_ID_USER + 3 )
#define  ID_BUTTON_3       (GUI_ID_USER + 4 )
#define  ID_BUTTON_4       (GUI_ID_USER + 5 )
#define  ID_BUTTON_5       (GUI_ID_USER + 6 )
#define  ID_BUTTON_6       (GUI_ID_USER + 7 )
#define  ID_BUTTON_7       (GUI_ID_USER + 8 )
#define  ID_BUTTON_8       (GUI_ID_USER + 9 )
#define  ID_BUTTON_9       (GUI_ID_USER + 10)
#define  ID_BUTTON_0       (GUI_ID_USER + 11)
#define  ID_BUTTON_Q       (GUI_ID_USER + 12)
#define  ID_BUTTON_W       (GUI_ID_USER + 13)
#define  ID_BUTTON_E       (GUI_ID_USER + 14)
#define  ID_BUTTON_R       (GUI_ID_USER + 15)
#define  ID_BUTTON_T       (GUI_ID_USER + 16)
#define  ID_BUTTON_Y       (GUI_ID_USER + 17)
#define  ID_BUTTON_U       (GUI_ID_USER + 18)
#define  ID_BUTTON_I       (GUI_ID_USER + 19)
#define  ID_BUTTON_O       (GUI_ID_USER + 20)
#define  ID_BUTTON_P       (GUI_ID_USER + 21)
#define  ID_BUTTON_A       (GUI_ID_USER + 22)
#define  ID_BUTTON_S       (GUI_ID_USER + 23)
#define  ID_BUTTON_D       (GUI_ID_USER + 24)
#define  ID_BUTTON_F       (GUI_ID_USER + 25)
#define  ID_BUTTON_G       (GUI_ID_USER + 26)
#define  ID_BUTTON_H       (GUI_ID_USER + 27)
#define  ID_BUTTON_J       (GUI_ID_USER + 28)
#define  ID_BUTTON_K       (GUI_ID_USER + 29)
#define  ID_BUTTON_L       (GUI_ID_USER + 30)
#define  ID_BUTTON_Z       (GUI_ID_USER + 31)
#define  ID_BUTTON_X       (GUI_ID_USER + 32)
#define  ID_BUTTON_C       (GUI_ID_USER + 33)
#define  ID_BUTTON_V       (GUI_ID_USER + 34)
#define  ID_BUTTON_B       (GUI_ID_USER + 35)
#define  ID_BUTTON_N       (GUI_ID_USER + 36)
#define  ID_BUTTON_M       (GUI_ID_USER + 37)
#define  ID_BUTTON_CAP     (GUI_ID_USER + 38)       // capital
#define  ID_BUTTON_DEL     (GUI_ID_USER + 39)       // delete
#define  ID_BUTTON_SPC     (GUI_ID_USER + 40)       // space
#define  ID_BUTTON_ENT     (GUI_ID_USER + 41)       // enter
#define  ID_BUTTON_CAC     (GUI_ID_USER + 42)       // cancel
#define  ID_MULTIEDIT      (GUI_ID_USER + 43)


// USER START (Optionally insert additional defines)
static WM_HWIN WinMyself;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,     "Window",     ID_WINDOW_0,      0,      23,     240,    297,    0,      0x0,    0 },

  { BUTTON_CreateIndirect,     "1",          ID_BUTTON_1,      24,     132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "2",          ID_BUTTON_2,      48,     132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "3",          ID_BUTTON_3,      72,     132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "4",          ID_BUTTON_4,      96,     132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "5",          ID_BUTTON_5,      120,    132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "6",          ID_BUTTON_6,      144,    132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "7",          ID_BUTTON_7,      168,    132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "8",          ID_BUTTON_8,      192,    132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "9",          ID_BUTTON_9,      216,    132,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "0",          ID_BUTTON_0,      0,      132,    24,     30,     0,      0x0,    0 },

  { BUTTON_CreateIndirect,     "q",          ID_BUTTON_Q,      0,      165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "w",          ID_BUTTON_W,      24,     165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "e",          ID_BUTTON_E,      48,     165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "r",          ID_BUTTON_R,      72,     165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "t",          ID_BUTTON_T,      96,     165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "y",          ID_BUTTON_Y,      120,    165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "u",          ID_BUTTON_U,      144,    165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "i",          ID_BUTTON_I,      168,    165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "o",          ID_BUTTON_O,      192,    165,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "p",          ID_BUTTON_P,      216,    165,    24,     30,     0,      0x0,    0 },

  { BUTTON_CreateIndirect,     "a",          ID_BUTTON_A,      12,     198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "s",          ID_BUTTON_S,      36,     198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "d",          ID_BUTTON_D,      60,     198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "f",          ID_BUTTON_F,      84,     198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "g",          ID_BUTTON_G,      108,    198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "h",          ID_BUTTON_H,      132,    198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "j",          ID_BUTTON_J,      156,    198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "k",          ID_BUTTON_K,      180,    198,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "l",          ID_BUTTON_L,      204,    198,    24,     30,     0,      0x0,    0 },

  { BUTTON_CreateIndirect,     "Cap",        ID_BUTTON_CAP,    0,      231,    36,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "z",          ID_BUTTON_Z,      36,     231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "x",          ID_BUTTON_X,      60,     231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "c",          ID_BUTTON_C,      84,     231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "v",          ID_BUTTON_V,      108,    231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "b",          ID_BUTTON_B,      132,    231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "n",          ID_BUTTON_N,      156,    231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "m",          ID_BUTTON_M,      180,    231,    24,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "Del",        ID_BUTTON_DEL,    204,    231,    36,     30,     0,      0x0,    0 },

  { BUTTON_CreateIndirect,     "Cac",        ID_BUTTON_CAC,    36,     264,    48,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     " ",          ID_BUTTON_SPC,    84,     264,    72,     30,     0,      0x0,    0 },
  { BUTTON_CreateIndirect,     "Ent",        ID_BUTTON_ENT,    156,    264,    36,     30,     0,      0x0,    0 },

  { MULTIEDIT_CreateIndirect,  "MultiEdit",  ID_MULTIEDIT,     5,      20,     230,    30,     0,      0x0,    0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
typedef enum {UPPERCASE, LOWERCASE} kdt_t;  // keyboard display type

/**
 * update keyboard to uppercase-display or lowercase-display
 * @param hWin: the windows handle of the keyboard
 * @param t: uppercase-display or lowercase-display should the keyboard use
 */
static void _updateKeyboard(WM_HWIN hWin, kdt_t t)
{
    const char *uppercase_tab = "QWERTYUIOPASDFGHJKLZXCVBNM";
    const char *lowercase_tab = "qwertyuiopasdfghjklzxcvbnm";
    const char *num_tab = "1234567890";
    volatile char buf[('z' - 'a' + 1) * 2] = {0};
    char (*p)[2] = (char (*)[2])buf;
    unsigned int i, len;

    if(t == UPPERCASE)
    {
        len = strlen(uppercase_tab);
        for(i = 0; i < len; i++)
        {
            buf[i * 2] = uppercase_tab[i];
        }
    }
    else if(t == LOWERCASE)
    {
        len = strlen(lowercase_tab);
        for(i = 0; i < len; i++)
        {
            buf[i * 2] = lowercase_tab[i];
        }
    }
    else
    {
        return;
    }

    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_Q), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_W), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_E), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_R), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_T), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_Y), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_U), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_I), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_O), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_P), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_A), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_S), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_D), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_F), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_G), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_H), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_J), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_K), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_L), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_Z), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_X), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_C), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_V), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_B), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_N), (char *)p++);
    BUTTON_SetText(WM_GetDialogItem(hWin, ID_BUTTON_M), (char *)p++);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  char ch[2] = {0};
  char str[20] = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M  ), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CAP), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DEL), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SPC), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ENT), 0);
      BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CAC), 0);
      break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_1:
    case ID_BUTTON_2:
    case ID_BUTTON_3:
    case ID_BUTTON_4:
    case ID_BUTTON_5:
    case ID_BUTTON_6:
    case ID_BUTTON_7:
    case ID_BUTTON_8:
    case ID_BUTTON_9:
    case ID_BUTTON_0:
    case ID_BUTTON_Q:
    case ID_BUTTON_W:
    case ID_BUTTON_E:
    case ID_BUTTON_R:
    case ID_BUTTON_T:
    case ID_BUTTON_Y:
    case ID_BUTTON_U:
    case ID_BUTTON_I:
    case ID_BUTTON_O:
    case ID_BUTTON_P:
    case ID_BUTTON_A:
    case ID_BUTTON_S:
    case ID_BUTTON_D:
    case ID_BUTTON_F:
    case ID_BUTTON_G:
    case ID_BUTTON_H:
    case ID_BUTTON_J:
    case ID_BUTTON_K:
    case ID_BUTTON_L:
    case ID_BUTTON_Z:
    case ID_BUTTON_X:
    case ID_BUTTON_C:
    case ID_BUTTON_V:
    case ID_BUTTON_B:
    case ID_BUTTON_N:
    case ID_BUTTON_M:
    case ID_BUTTON_SPC:
        if(NCode == WM_NOTIFICATION_RELEASED)
        {
            BUTTON_GetText(WM_GetDialogItem(pMsg->hWin, Id), ch, sizeof(ch));
            GUI_SendKeyMsg(ch[0], 1);
        }
        break;

    case ID_BUTTON_DEL:
        if(NCode == WM_NOTIFICATION_RELEASED)
        {
            GUI_SendKeyMsg(8, 1);
        }
        break;

    case ID_BUTTON_CAP:
        if(NCode == WM_NOTIFICATION_RELEASED)
        {
            if(BUTTON_GetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CAP), BUTTON_CI_UNPRESSED) == GUI_RED)
            {
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CAP), 0, GUI_BLACK);
                _updateKeyboard(pMsg->hWin, LOWERCASE);
            }
            else
            {
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CAP), 0, GUI_RED);
                _updateKeyboard(pMsg->hWin, UPPERCASE);
            }
        }
        break;

    case ID_BUTTON_ENT:
        if(NCode == WM_NOTIFICATION_RELEASED)
        {
            MULTIEDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT), str, sizeof(str));
            if(strlen(str) < 100)
            {
                extern void mutiedit_enter_handle (char *string);

                mutiedit_enter_handle(str);
            }
            WM_DeleteWindow(WinMyself);
        }
        break;

    case ID_BUTTON_CAC:
        if(NCode == WM_NOTIFICATION_RELEASED)
        {
            WM_DeleteWindow(WinMyself);
        }
        break;
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  WinMyself = hWin;
  return hWin;
}

// USER START (Optionally insert additional public code)
WM_HWIN CreateWindowFullKeyboard(void)
{
    return CreateWindow();
}
// USER END

/*************************** End of file ****************************/
